databases:
  - name: projectcalm-db
    plan: free
    databaseName: projectcalm
    user: projectcalm

services:
  - type: web
    name: projectcalm
    env: static
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: projectcalm-api
    env: node
    plan: free
    buildCommand: cd server && npm ci
    startCommand: node server/index.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: projectcalm-db
          property: connectionString
