services:
  - type: static_site
    name: project-calm-web
    env: static
    buildCommand: npm ci && npm run build && npm run mobile:bundle
    staticPublishPath: www
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html