name: Feature request
description: Suggest an idea to improve Project Calm
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this solve? Why is this useful?
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Any additional context or examples

